### PR TITLE
feat: navbar logo redirect to home

### LINKED ISSUE #1: feature: make navbar logo redirect to home

### PR DESCRIPTION
**Pull request by neeravbhaskarla**
Fixes #1

### CODE REVIEW

**Review by jibranabsarulislam — CHANGES_REQUESTED** [review]
i'm sorry, I forgot to specify that the text is included with the Logo. can you make both the text and the logo redirect to home, maintaining the styling? please view my suggestion and implement at your discretion

**Review by jibranabsarulislam — APPROVED** [review]

**Comment by jibranabsarulislam** [comment]
@all-contributors add @neeravbhaskarla for developing nav logo redirect

**Comment by jibranabsarulislam** [comment]
@all-contributors add @neeravbhaskarla for developing nav logo redirect code

**Comment by neeravbhaskarla** [comment]
Thanks for adding me as a contributor 😊

**Comment by neeravbhaskarla** [comment]
yeah sure @jibranabsarulislam

**Pull request merged**
